version: '3.8'

services:
  mcp-visio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 8050
    container_name: mcp-visio
    ports:
      - "8050:8050"
    environment:
      - TRANSPORT=sse
      - HOST=0.0.0.0
      - PORT=8050
      - VISIO_SERVICE_HOST=host.docker.internal
      - VISIO_SERVICE_PORT=8051
      - OLLAMA_API_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=gemma3
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway" 